<?php
    $data = $block->getShoparizeData();
    $action = $data['full_action_name'];
?>
<script>
    window.onload = function () { console.log("selamıunaleyküm");}
</script>
<?php if($data['enable']) : ?>
    <script>
        require(['jquery', 'https://partner-cdn.shoparize.com/js/shoparize.js'], function($, shoparize) {
            var customerId = '<?php echo $data['customerid']; ?>';
            SHOPARIZE_API().init(customerId);
        });
    </script>
    <?php if ($action == 'checkout_onepage_success' || $action == 'onepagecheckout_index_success') : ?>
    	<?php
    	$orderData = $block->getOrderData();
        if ($orderData !== null) : ?>
        	<?php
            	$orderItems = $orderData['items'];
		        $custom_order = [
		            'event' => 'purchase',
		            'ecommerce' => [
		                'transaction_id' => $orderData['id'],
		                'value' => $orderData['value'],
		                'tax' => $orderData['tax'],
		                'shipping' => $orderData['shipping'],
		                'currency' => $orderData['currency']
		            ]
		        ];
		        foreach($orderItems as $item) {
		            $custom_order['ecommerce']['items'][] = [
		                'item_id' => $item['id'],
		                'item_name' => $item['name'],
		                'currency' => $orderData['currency'],
		                'price' => $item['price'],
		                'quantity' => $item['quantity']
		            ];
		        }
		    ?>
		    <?php
		    	echo "<script>";
		            echo "var dataLayerShoparize = [" . json_encode($custom_order) . "];";
		            echo "window.onload = function () {  SHOPARIZE_API().conv(".$data['customerid']."); }";
		        echo "</script>";
		    ?>
        <?php endif; ?>
    <?php endif; ?>
<?php endif; ?>
